'use client';

import * as React from 'react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardFooter, CardHeader, CardTitle } from '@/components/ui/card';
import { Link } from '@inertiajs/react';
import {
  Quote,
  Sparkles,
  ClipboardList,
  Share2,
  BarChart3,
} from 'lucide-react';

const ProofWall: React.FC = () => {
  // Optional: lightweight JSON-LD for case studies
  const jsonLd = {
    '@context': 'https://schema.org',
    '@type': 'ItemList',
    itemListElement: [
      {
        '@type': 'CaseStudy',
        name: 'ClickHouse — Research to Actionable Personas',
        description:
          'Reduced synthesis time and aligned PM/UX with briefs generated by PERSONAAITOR.',
        about: { '@type': 'SoftwareApplication', name: 'PERSONAAITOR' },
      },
      {
        '@type': 'CaseStudy',
        name: 'DataForge — Personas that Ship Work',
        description:
          'Turned interviews into JTBD, objections, and copy angles; wins in 2 sprints.',
        about: { '@type': 'SoftwareApplication', name: 'PERSONAAITOR' },
      },
      {
        '@type': 'CaseStudy',
        name: 'SecurePay — Living Personas Across Teams',
        description:
          'Single source of truth with versions/embeds; fewer review cycles.',
        about: { '@type': 'SoftwareApplication', name: 'PERSONAAITOR' },
      },
    ],
  };

  return (
    <section
      id="proof"
      className="mx-auto w-full max-w-6xl px-6 py-16 md:py-16 flex flex-col items-center justify-center text-center"
      aria-labelledby="proof-heading"
    >
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />

      <div className="mb-8">
        <Badge variant="secondary" className="rounded-full">Proof</Badge>
        <h2
          id="proof-heading"
          className="mt-4 text-3xl font-semibold tracking-tight sm:text-4xl"
        >
          From guesswork to personas that ship
        </h2>
        <p className="mt-3 max-w-[72ch] text-[var(--muted-foreground)]">
          Real customer stories—problem, plays we ran, and the measurable outcomes.
        </p>
      </div>

      {/* Case study tiles */}
      <ul role="list" className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
        {/* CS #1 */}
        <li role="listitem">
          <Card className="h-full border border-[var(--border)] bg-[var(--card)]/80 backdrop-blur-xs supports-[backdrop-filter]:bg-[var(--card)]/60">
            <CardHeader>
              <div className="flex items-center gap-3">
                <img
                  src="https://ui-avatars.com/api/?name=Click+House&background=000000&color=fff&rounded=true"
                  alt="ClickHouse"
                  className="h-7 w-7"
                  loading="lazy"
                  decoding="async"
                />
                <CardTitle className="text-base">ClickHouse</CardTitle>
              </div>
              <p className="mt-2 text-sm text-[var(--muted-foreground)]">
                <strong>Problem:</strong> Interviews scattered; strategy stalled by opinion wars.
              </p>
            </CardHeader>

            <CardContent className="space-y-3">
              <div className="text-xs">
                <p className="mb-1 font-medium">Plays used</p>
                <div className="flex flex-wrap gap-2">
                  <span className="rounded-full border px-2.5 py-1 text-[var(--muted-foreground)]">
                    Ingest &amp; Normalize
                  </span>
                  <span className="rounded-full border px-2.5 py-1 text-[var(--muted-foreground)]">
                    Generate &amp; Align
                  </span>
                  <span className="rounded-full border px-2.5 py-1 text-[var(--muted-foreground)]">
                    Share &amp; Ship
                  </span>
                </div>
              </div>

              <div className="rounded-lg border p-3 text-sm">
                <div className="mb-1 flex items-center gap-2 font-medium">
                  <BarChart3 className="h-4 w-4" /> Outcome
                </div>
                <ul className="list-disc pl-5 text-[var(--muted-foreground)]">
                  <li>−70% research synthesis time</li>
                  <li>Faster roadmap alignment</li>
                </ul>
              </div>

              <blockquote className="relative text-sm">
                <Quote className="absolute -left-1 -top-1 h-4 w-4 opacity-60" aria-hidden="true" />
                <p className="pl-5">
                  PERSONAAITOR turned chaos into briefs we could ship with—no more opinion deadlocks.
                </p>
              </blockquote>
            </CardContent>

            <CardFooter className="justify-between">
              <div className="flex items-center gap-2 text-xs text-[var(--muted-foreground)]">
                <Sparkles className="h-4 w-4" /> PM • UX • Growth
              </div>
              <Link href="/case-studies/clickhouse">
                <Button size="sm" variant="ghost">Read story</Button>
              </Link>
            </CardFooter>
          </Card>
        </li>

        {/* CS #2 */}
        <li role="listitem">
          <Card className="h-full border border-[var(--border)] bg-[var(--card)]/80">
            <CardHeader>
              <div className="flex items-center gap-3">
                <img
                  src="https://ui-avatars.com/api/?name=Data+Forge&background=000000&color=fff&rounded=true"
                  alt="DataForge"
                  className="h-7 w-7"
                  loading="lazy"
                  decoding="async"
                />
                <CardTitle className="text-base">DataForge</CardTitle>
              </div>
              <p className="mt-2 text-sm text-[var(--muted-foreground)]">
                <strong>Problem:</strong> Personas looked great but didn’t guide UX or copy.
              </p>
            </CardHeader>

            <CardContent className="space-y-3">
              <div className="text-xs">
                <p className="mb-1 font-medium">Plays used</p>
                <div className="flex flex-wrap gap-2">
                  <span className="rounded-full border px-2.5 py-1 text-[var(--muted-foreground)]">
                    Generate &amp; Align
                  </span>
                  <span className="rounded-full border px-2.5 py-1 text-[var(--muted-foreground)]">
                    Brief Templates
                  </span>
                  <span className="rounded-full border px-2.5 py-1 text-[var(--muted-foreground)]">
                    Acceptance Criteria
                  </span>
                </div>
              </div>

              <div className="rounded-lg border p-3 text-sm">
                <div className="mb-1 flex items-center gap-2 font-medium">
                  <BarChart3 className="h-4 w-4" /> Outcome
                </div>
                <ul className="list-disc pl-5 text-[var(--muted-foreground)]">
                  <li>Winning headline &amp; onboarding tests in 2 sprints</li>
                  <li>CTR ↑ • activation ↑</li>
                </ul>
              </div>

              <blockquote className="relative text-sm">
                <Quote className="absolute -left-1 -top-1 h-4 w-4 opacity-60" aria-hidden="true" />
                <p className="pl-5">
                  Finally personas that drive decisions—not just slides. We shipped confidently.
                </p>
              </blockquote>
            </CardContent>

            <CardFooter className="justify-between">
              <div className="flex items-center gap-2 text-xs text-[var(--muted-foreground)]">
                <ClipboardList className="h-4 w-4" /> UX • Copy • PM
              </div>
              <Link href="/case-studies/dataforge">
                <Button size="sm" variant="ghost">Read story</Button>
              </Link>
            </CardFooter>
          </Card>
        </li>

        {/* CS #3 */}
        <li role="listitem">
          <Card className="h-full border border-[var(--border)] bg-[var(--card)]/80">
            <CardHeader>
              <div className="flex items-center gap-3">
                <img
                  src="https://ui-avatars.com/api/?name=Secure+Pay&background=000000&color=fff&rounded=true"
                  alt="SecurePay"
                  className="h-7 w-7"
                  loading="lazy"
                  decoding="async"
                />
                <CardTitle className="text-base">SecurePay</CardTitle>
              </div>
              <p className="mt-2 text-sm text-[var(--muted-foreground)]">
                <strong>Problem:</strong> Stale PDFs; no single source of truth across teams.
              </p>
            </CardHeader>

            <CardContent className="space-y-3">
              <div className="text-xs">
                <p className="mb-1 font-medium">Plays used</p>
                <div className="flex flex-wrap gap-2">
                  <span className="rounded-full border px-2.5 py-1 text-[var(--muted-foreground)]">
                    Share &amp; Ship
                  </span>
                  <span className="rounded-full border px-2.5 py-1 text-[var(--muted-foreground)]">
                    Live Embeds
                  </span>
                  <span className="rounded-full border px-2.5 py-1 text-[var(--muted-foreground)]">
                    Versioning
                  </span>
                </div>
              </div>

              <div className="rounded-lg border p-3 text-sm">
                <div className="mb-1 flex items-center gap-2 font-medium">
                  <BarChart3 className="h-4 w-4" /> Outcome
                </div>
                <ul className="list-disc pl-5 text-[var(--muted-foreground)]">
                  <li>Review cycles ↓ • duplication ↓</li>
                  <li>On-message campaigns across PM/UX/Growth</li>
                </ul>
              </div>

              <blockquote className="relative text-sm">
                <Quote className="absolute -left-1 -top-1 h-4 w-4 opacity-60" aria-hidden="true" />
                <p className="pl-5">
                  The live, shared persona ended the version hunt—and kept launches aligned.
                </p>
              </blockquote>
            </CardContent>

            <CardFooter className="justify-between">
              <div className="flex items-center gap-2 text-xs text-[var(--muted-foreground)]">
                <Share2 className="h-4 w-4" /> Product • Marketing • Sales
              </div>
              <Link href="/case-studies/securepay">
                <Button size="sm" variant="ghost">Read story</Button>
              </Link>
            </CardFooter>
          </Card>
        </li>
      </ul>

      {/* Why folks choose us */}
      <div className="mt-10">
        <h3 className="text-xl font-semibold tracking-tight">Why teams choose PERSONAAITOR</h3>
        <ul className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
          <li className="rounded-xl border p-3 text-sm">
            <span className="font-medium">Accuracy</span>
            <p className="mt-1 text-[var(--muted-foreground)]">Citations &amp; confidence scoring reduce bias.</p>
          </li>
          <li className="rounded-xl border p-3 text-sm">
            <span className="font-medium">Actionability</span>
            <p className="mt-1 text-[var(--muted-foreground)]">Briefs with examples &amp; criteria unblock execution.</p>
          </li>
          <li className="rounded-xl border p-3 text-sm">
            <span className="font-medium">Team alignment</span>
            <p className="mt-1 text-[var(--muted-foreground)]">Comments, versions, approvals, live embeds.</p>
          </li>
          <li className="rounded-xl border p-3 text-sm">
            <span className="font-medium">Fits your stack</span>
            <p className="mt-1 text-[var(--muted-foreground)]">Exports to Figma/Notion/CSV; easy to maintain.</p>
          </li>
        </ul>
      </div>

      {/* CTAs under grid */}
      <div className="mt-8 flex flex-wrap gap-3">
        <Link href="/case-studies">
          <Button className="rounded-full">See all case studies</Button>
        </Link>
        <Link href="/audit">
          <Button variant="outline" className="rounded-full">Get my free audit</Button>
        </Link>
        {/* Bridge to FAQ next */}
        <Link href="#faq">
          <Button variant="ghost" className="rounded-full">Questions? Jump to FAQ</Button>
        </Link>
      </div>
    </section>
  );
};

export default ProofWall;
